apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-actions-exporter.fullname" . }}
  labels:
    {{- include "github-actions-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "github-actions-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ template "github-actions-exporter.name" . }}
        release: {{ .Release.Name }}
        {{- include "github-actions-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"          
          env:
          {{- range $name, $value := .Values.env }}
          {{- if not (empty $value) }}
          - name: {{ $name | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          # Params for env vars populated from k8s secrets
          {{- range $key, $value := .Values.envVarsFromSecret }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $value.secretKeyRef | quote }}
                key: {{ $value.key | quote }}
          {{- end }}     
          ports:
            - name: http
              containerPort: {{ .Values.env.PORT }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
